### ISSUE TITLE
`timestampSelect` puts cursor in the wrong place

### ISSUE THREAD

**Issue by chreekat** [NorfairKing/smos#13]
This seems to depend on the contents of the smos file. Here's one that triggers the bug on master@048fd646a587e63a7dc201ab48cfee6bb558ba70:

```
- header: xxx xxxxxxxx xxxxxxxx xxxx xxxxxx
  state-history:
  - new-state: STARTED
    timestamp: 2019-07-03 08:02:42.681757242000+0000
  - new-state: TODO
    timestamp: 2019-07-03 08:02:42.105753829000+0000
  - new-state: TODO
    timestamp: 2019-07-03 08:02:41.045923673000+0000
  - new-state: STARTED
    timestamp: 2019-07-02 17:54:24.734551713000+0000
  - new-state: NEXT
    timestamp: 2019-07-02 10:52:14.379951466000+0000
  - new-state: TODO
    timestamp: 2019-07-02 10:52:09.401162609000+0000
  tags:
  - work
  logbook:
  - start: 2019-07-03 08:06:05.075234670000+0000
  - start: 2019-07-03 07:25:55.901819084000+0000
    end: 2019-07-03 08:06:05.075234670000+0000
  - start: 2019-07-02 16:33:29.005395122000+0000
    end: 2019-07-02 17:52:06.375957744000+0000
  - start: 2019-07-02 11:09:00.728128801000+0000
    end: 2019-07-02 12:40:24.872332712000+0000
  - start: 2019-07-02 10:53:09.112838235000+0000
    end: 2019-07-02 10:53:23.469784638000+0000
- header: Modify my timestamp with ss
  timestamps:
    SCHEDULED: 2019-07-06
- header: xxx xx xxxx xxxxxx xxxxxxx
  state-history:
  - new-state: TODO
    timestamp: 2019-07-03 06:44:03.329347470000+0000
- header: xxxx xxxxx xxxxx xxxxxxx xxxxxx xxx xxxxxx
  timestamps:
    SCHEDULED: 2019-07-03
- header: xxxxxx xxx xxxxxx
  state-history:
  - new-state: TODO
    timestamp: 2019-07-03 06:43:56.923525622000+0000
- header: xxx xx xxxx xxx xxxxx
  state-history:
  - new-state: TODO
    timestamp: 2019-07-03 06:43:57.982459378000+0000
```

When I try to change the SCHEDULED timestamp for the 2nd item, the cursor gets placed before the colon:

```
SCHEDULED:
         ^-- cursor between D and :
```
