### ISSUE TITLE
smos-query clock - does not show expected output after update

### ISSUE THREAD

**Issue by aniketd** [NorfairKing/smos#146]
On fef15525a0101351db9decb3afa2418244f80796, I have a smos file with contents:
![2020-08-20-180029_650x216_scrot](https://user-images.githubusercontent.com/922486/90896877-fcfff100-e3e1-11ea-87b0-769bdb978f42.png)
yet `smos-query clock --today` does not show the correct calculation for the output, irrespective of whether I use `--begin/--end` or `--today/--yesterday` flag combinations:
![2020-08-20-181825_672x81_scrot](https://user-images.githubusercontent.com/922486/90896890-02f5d200-e3e2-11ea-81e6-fc1c2fcd7b1b.png)

**Comment by NorfairKing** [comment]
Hi @aniketd This is interesting.
Could you upload the smos file (minus whatever you'd like to be redacted) here?
You can open them with your editor of choice and just replace the letters by `X`-es.

My first instinct: Is the file in your workflow directory?

**Comment by aniketd** [comment]
> My first instinct: Is the file in your workflow directory?

Yes.

After looking at more of the behavior I'm almost convinced this has something to do with clocks that continue past midnight, (but obviously I can't be sure :)).

Will post the file soon.

**Comment by NorfairKing** [comment]
> After looking at more of the behavior I'm almost convinced this has something to do with clocks that continue past midnight, (but obviously I can't be sure :)).

It would also help if we knew what day you ran that command, but it looks like there is no clock that continues past midnight ...

**Comment by aniketd** [comment]
> it looks like there is no clock that continues past midnight 

You are right. I also notice no clock running past midnight. Sorry, that was just a hunch without looking at the details in the file. I'm seeing this happen more than once.

> It would also help if we knew what day you ran that command

I ran this command on 2020-08-20. This is reproducible on my side by executing `smos-query clock --begin 2020-08-20 --end 2020-08-20`. Only the entry from other files is accounted for, as shown in the screen-captures.

Attaching the file in question.

```
- entry:
    header: MAIN TITLE
    properties:
      brainpower: '9'
      client: someclient
      timewindow: 2h
    state-history:
    - state: TODO
      time: 2020-08-13 10:30:43.476222241000
  forest:
  - header: Start survey of code proper to understand what's going on currently
    state-history:
    - state: DONE
      time: 2020-08-19 13:35:01.850421143000
    - state: STARTED
      time: 2020-08-13 10:31:15.602025159000
    logbook:
    - start: 2020-08-13 18:28:33.592049790000
      end: 2020-08-14 01:59:33.000172251000
    - start: 2020-08-13 11:37:22.392128723000
      end: 2020-08-13 13:57:20.222828005000
    - start: 2020-08-13 10:31:16.124106961000
      end: 2020-08-13 10:57:13.071394680000
  - header: Build on top of colleague's inputs on how to proceed and wrap up the issue
    state-history:
    - state: DONE
      time: 2020-08-19 21:18:39.528966013000
    - state: STARTED
      time: 2020-08-19 13:35:21.432404474000
    logbook:
    - start: 2020-08-19 19:17:14.525408937000
      end: 2020-08-19 20:49:13.955865860000
    - start: 2020-08-19 18:37:41.589969552000
      end: 2020-08-19 19:04:49.062501410000
    - start: 2020-08-19 16:40:52.707227660000
      end: 2020-08-19 16:40:54.072390762000
    - start: 2020-08-19 14:52:04.867567956000
      end: 2020-08-19 16:40:52.707227660000
    - start: 2020-08-19 13:35:02.928637206000
      end: 2020-08-19 14:09:21.128634288000
  - header: Continue and finish MR
    state-history:
    - state: DONE
      time: 2020-08-20 22:54:10.197153199000
    - state: STARTED
      time: 2020-08-20 12:47:00.966825171000
    logbook:
    - start: 2020-08-20 12:46:55.962206703000
      end: 2020-08-20 22:54:02.320840962000

```
