### ISSUE TITLE
Smos-query isn't correctly parsing columns from the config

### ISSUE THREAD

**Issue by vidocco** [NorfairKing/smos#201]
Hiya,

As the title states, `smos-query` isn't correctly parsing the `column` attribute from the config file (while it is being correctly parsed in `smos`). Contexts are being correctly pulled from the config though (`smos-query work work` works as expected and shows only projects within the `work` directory).

Current config file:
```
work:
  contexts:
    home: 'file:home'
    work: 'file:work'
    gd: 'file:gd'
  columns:
    - 'file'
    - 'state'
    - 'header'
    - 'property:timewindow'
```

Please let me know if you need anything else on my side.
