### ISSUE TITLE
Entries instantiated from a template are in the TODO state

### ISSUE THREAD

**Issue by ketzacoatl** [NorfairKing/smos#25]
ATM, a template such as:

```
- entry: Example template %F
  forest:
  - Subdir %y
```

Run with `smos-scheduler` like:

```
$ smos-scheduler --workflow-dir `pwd` --config-file example-config.yaml --state-file example-state.yaml
```

Results in a file like:

```
- entry: Example template 2019-12-22
  forest:
  - Subdir 19
```

Instead, it would be better to put those new entries in the TODO state.

The `.smos` file produced by `smos-scheduler` would then look like:

```
- entry:
    header: Example template 2019-12-22
    state-history:
    - state: TODO
      time: 2019-12-22 22:00:08.135470693000
  forest:
  - header: Subdir 19
    state-history:
    - state: TODO
      time: 2019-12-22 22:00:10.296044116000
```
