### ISSUE TITLE
Time filter not working in smos work report

### ISSUE THREAD

**Issue by distefam** [NorfairKing/smos#263]
When I run `smos-query work CONTEXT TIME_FILTER` it filters properly based on my pre-defined contexts, however, I still see a lot of tasks that have a greater time property than I specify.

Here is one of my contexts, `office`, for reference:

```yaml
work:
  contexts:
    office: '((((ancestor:tag:office or tag:read) or (tag:computer or tag:exploration)) or (tag:call or tag:email)) or tag:anywhere)'
```

If I run `smos-query work office 10m` I see all tasks that meet the context filter, including those that take greater than 10 minutes.

I am running smos-query tool version: 0.10.0

**Comment by distefam** [comment]
Aha, I had to add `time-filter` to my `config.yaml`:

```yaml
work:
  contexts:
    office: ...
  time-filter:
    'timewindow'
```
