### ISSUE TITLE
`smos-query report` should print the available reports

### ISSUE THREAD

**Issue by wfranzini** [NorfairKing/smos#42]
The `smos-query reports` should offer a way to discover available
pre-configured reports.

Something like:

```
$ smos-query report --list
```
```

**Comment by NorfairKing** [comment]
I agree, will see when I can implement it.

**Comment by NorfairKing** [comment]
This is now also fixed on master.
I'm not closing this yet because I'd like your opinion on the exact output.

**Comment by wfranzini** [comment]
I'm not sure what to expect.  When I run the smos-query report it
simply prints "*No report configured*".

Then I tried to configure the work report as mentioned in
<https://smos.cs-syd.eu/smos-query.html> but got confusing results:

``` yaml
work:
  checks:
    - has-property:timewindow
  columns:
    - file
    - state
    - header
    - property:timewindow
  sorter: property-as-time:timewindow
```


``` shellsession
smos-query report
Aeson exception:
Error in $.work.checks[0]: Could not parse EntryFilter: FTEKeyWordExpected (Piece {pieceText = "has-property"})
```

After changing the name of the report to something different
(e.g. foo-report) the above command succeeded, but I've got the same
"No report configured" message.

**Comment by NorfairKing** [comment]
@wfranzini I think it's unclear what the preconfigured reports are.
Any report that is listed as a command is _not_ a preconfigured report.
Preconfigured reports are for when you find yourself passing the same options to `smos-query entry` a lot and would like to configure that in a file instead of a as flags.
For example if you have a tag `accounting` for things that you need to see during your accounting, then you can do this in the config file:

```
        reports:
          accounting:
            description: 'Anything I need to see during my accounting'
            filter: tag:accounting
```
Then you can run `smos-query report accounting` to run that report.
You can also run `smos-query report` to see this:

```
$ smos-query report
Available reports:
accounting: Anything I need to see during my accounting
```

I think what you're looking for is `smos-query --help` to see what kind of commands there are.
To configure the work command, you want to put this at the top-level:
```
contexts:
  home: tag:home
  office: tag:office
       
work:
  time-filter: timewindow
  checks:
    - property:timewindow
  columns:
    - file
    - state
    - header
    - property:timewindow
  sorter: 'reverse:property-as-time:timewindow'
```

Then the work command will work like this:
```
smos-query work home 2h
```

Does that make sense? Again, we're still working on docs.
